# Generated by Django 4.2.5 on 2023-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_projectdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase',
            field=models.CharField(max_length=20),
        ),
    ]
