# Generated by Django 4.2.4 on 2023-11-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_pump_price_alter_phase_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
