# Generated by Django 4.2.4 on 2023-11-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_pump_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
