# Generated by Django 4.2.4 on 2023-12-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0005_pump_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
